name: Android CI ğŸ¤–

on:
  release:
    types: [published] ğŸš€
  workflow_dispatch:  # æ·»åŠ æ‰‹åŠ¨è§¦å‘é€‰é¡¹
    inputs:
      version:
        description: 'æ‰‹åŠ¨æŒ‡å®šç‰ˆæœ¬å·'
        required: true
        default: 'manual-build'

jobs:
  build:
    runs-on: ubuntu-latest ğŸ’»

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # æ‹‰å–ä»£ç ä»“åº“ ğŸ“¥

      - name: set up JDK 21 â˜•
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew ğŸ”‘
        run: chmod +x gradlew

      - name: Build with Gradle ğŸ”¨
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ./gradlew assembleRelease -P version=${{ github.event.inputs.version }}
          else
            ./gradlew assembleRelease -P version=${{ github.ref_name }}
          fi

      - name: Sign Normal APK ğŸ“¦
        id: sign_normal_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/normal/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Sign Compatible APK ğŸ“¦
        id: sign_compatible_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/compatible/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Upload Normal to Release ğŸ“¤
        uses: termux/upload-release-action@v4.2.0
        with:
          asset_name: |
            Sesame-Normal-$(if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
              echo "${{ github.event.inputs.version }}";
            else
              echo "${{ github.event.release.tag_name }}";
            fi).apk
          file: ${{ steps.sign_normal_apk.outputs.signedFile }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: |
            $(if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
              echo "refs/tags/${{ github.event.inputs.version }}";
            else
              echo "${{ github.ref }}";
            fi)
          overwrite: true
          checksums: sha256
          checksums_file_name: |
            CHECKSUMS-Sesame-Normal-$(if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
              echo "${{ github.event.inputs.version }}";
            else
              echo "${{ github.event.release.tag_name }}";
            fi).%algo%

      - name: Upload Compatible to Release ğŸ“¤
        uses: termux/upload-release-action@v4.2.0
        with:
          asset_name: |
            Sesame-Compatible-$(if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
              echo "${{ github.event.inputs.version }}";
            else
              echo "${{ github.event.release.tag_name }}";
            fi).apk
          file: ${{ steps.sign_compatible_apk.outputs.signedFile }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: |
            $(if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
              echo "refs/tags/${{ github.event.inputs.version }}";
            else
              echo "${{ github.ref }}";
            fi)
          overwrite: true
          checksums: sha256
          checksums_file_name: |
            CHECKSUMS-Sesame-Compatible-$(if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
              echo "${{ github.event.inputs.version }}";
            else
              echo "${{ github.event.release.tag_name }}";
            fi).%algo%
